function PQprtMOVCi (Nchan, i, MOVC)
% Print MOV precursors

% P. Kabal $Revision: 1.1 $  $Date: 2003/12/07 13:34:47 $

fprintf ('Frame: %d\n', i);

if (Nchan == 1)
    fprintf ('  Ntot   : %g %g\n', ...
        MOVC.Loud.NRef(1,i+1), MOVC.Loud.NTest(1,i+1));
    fprintf ('  ModDiff: %g %g %g\n', ...
        MOVC.MDiff.Mt1B(1,i+1), MOVC.MDiff.Mt2B(1,i+1), MOVC.MDiff.Wt(1,i+1));
    fprintf ('  NL     : %g\n', MOVC.NLoud.NL(1,i+1));
    fprintf ('  BW     : %g %g\n', ...
        MOVC.BW.BWRef(1,i+1), MOVC.BW.BWTest(1,i+1));
    fprintf ('  NMR    : %g %g\n', ...
        MOVC.NMR.NMRavg(1,i+1), MOVC.NMR.NMRmax(1,i+1));
    fprintf ('  PD     : %g %g\n', MOVC.PD.Pc(i+1), MOVC.PD.Qc(i+1));
    fprintf ('  EHS    : %g\n', 1000 * MOVC.EHS.EHS(1,i+1));
else
    fprintf ('  Ntot   : %g %g // %g %g\n', ...
	    MOVC.Loud.NRef(1,i+1), MOVC.Loud.NTest(1,i+1), ...
	    MOVC.Loud.NRef(2,i+1), MOVC.Loud.NTest(2,i+1));
    fprintf ('  ModDiff: %g %g %g // %g %g %g\n', ...
	    MOVC.MDiff.Mt1B(1,i+1), MOVC.MDiff.Mt2B(1,i+1), MOVC.MDiff.Wt(1,i+1), ...
	    MOVC.MDiff.Mt1B(2,i+1), MOVC.MDiff.Mt2B(2,i+1), MOVC.MDiff.Wt(2,i+1));
    fprintf ('  NL     : %g // %g\n', ...
	    MOVC.NLoud.NL(1,i+1), ...
	    MOVC.NLoud.NL(2,i+1));
    fprintf ('  BW     : %g %g // %g %g\n', ...
	    MOVC.BW.BWRef(1,i+1), MOVC.BW.BWTest(1,i+1), ...
	    MOVC.BW.BWRef(2,i+1), MOVC.BW.BWTest(2,i+1));
    fprintf ('  NMR    : %g %g // %g %g\n', ...
	    MOVC.NMR.NMRavg(1,i+1), MOVC.NMR.NMRmax(1,i+1), ...
	    MOVC.NMR.NMRavg(2,i+1), MOVC.NMR.NMRmax(2,i+1));
    fprintf ('  PD     : %g %g\n', MOVC.PD.Pc(i+1), MOVC.PD.Qc(i+1));
    fprintf ('  EHS    : %g // %g\n', ...
	    1000 * MOVC.EHS.EHS(1,i+1), ...
	    1000 * MOVC.EHS.EHS(2,i+1));
end
